module.exports = {
    USER_CONNECTED: "USER_CONNECTED",
    SONG_RECEIVED: "SONG_RECEIVED",
    SONG_SENT:"SONG_SENT",
    SONG_ENDS: "SONG_ENDS",
    SONG_PLAYS: "SONG_PLAYS",
    USER_DISCONNECTED: "USER_DISCONNECTED",
    VOTEUP: "VOTEUP",
    VOTEDOWN: "VOTEDOWN",
    VERIFY_USER: "VERIFY_USER",
    VOTEDOWN: "VOTEDOWN",
    LOGOUT: "LOGOUT"
}